GroupyWeb/GroupyWeb/Models/Setting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GroupyWeb.Models
{
    public class Setting
    {
        public Setting()
        {
            Groupsets = new HashSet<GroupSet>();
            Persons = new HashSet<Person>();
        }

        public int Id { get; set; }
        public String UserId { get; set; }

        public GroupyUser GroupyUser { get; set; }
        public ICollection<GroupSet> Groupsets { get; set; }
        public ICollection<Person> Persons { get; set; }
    }
}

GroupyWeb/GroupyWeb/Controllers/GroupMakerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GroupyWeb.Data;
using GroupyWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace GroupyWeb.Controllers
{
    [Authorize]
    public class GroupMakerController : Controller
    {
        private readonly GroupyContext _context;

        public GroupMakerController(GroupyContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            //var setting = await _context.Settings.SingleOrDefaultAsync(m => m.Id == id).;
            var setting = await _context.Settings.Include(m => m.Persons)
                                                 .Include(m => m.Groupsets).ThenInclude(gs => gs.Groups)
                                                 .SingleOrDefaultAsync(m => m.Id == id);
            //var setting = _context.Settings.Where(m => m.Id == id).Include(m => m.Persons).Include(m => m.Groupsets).ThenInclude(g => g.Groups).FirstOrDefault();
            if (setting == null)
            {
                return NotFound();
            }

            ViewData["Setting"] = setting;
            ViewData["Persons"] = setting.Persons.ToList();
            ViewData["GroupSets"] = setting.Groupsets.ToList();
            var groups = new List<Group>();
            var membersInGroups = new List<MembersInGroups>();
            foreach (var groupset in setting.Groupsets) //get all groups in setting
            {
                foreach (var group in groupset.Groups)
                {
                    groups.Add(group);
                    foreach (var memInGr in _context.MembersInGroups.Where(m => m.Group == group))
                        //get all member connections to this group
                    {
                        membersInGroups.Add(memInGr);
                    }
                }
            }
            ViewData["Groups"] = groups;
            ViewData["MembersInGroups"] = membersInGroups;
            return View();
        }

        [HttpPost]
        //async Task<IActionResult>
        public async Task<IActionResult> AssignToGroups([FromBody]jsonInputClass input)
        {
            //todo - do some check to see if setting id is valid and stuff

            Setting setting = await _context.Settings
                .Include(s => s.Persons).ThenInclude(p => p.PersonRelationsP1)
                .Include(s => s.Groupsets).ThenInclude(gr => gr.Groups).ThenInclude(g => g.MembersInGroups)
                //.Include(m => m.Persons).ThenInclude(p => p.PersonRelationsP2)
                .SingleOrDefaultAsync(m => m.Id == input.Id);
            //GroupSet newGroupSet = new GroupSet();
            //setting.Groupsets.Add(newGroupSet);
            Person[] activePeople = setting.Persons.Where(p => p.Active == true).ToArray();

            List<PersonRelation> relations = new List<PersonRelation>();
            foreach (var person in activePeople)
            {
                foreach (var relation in person.PersonRelationsP1)
                {
                    relations.Add(relation);
                }
            }
            GroupSet groupSet = GroupMaker.AssignToGroups(activePeople, relations, 5, out var membersInGroups);
            foreach (var memberInGroup in membersInGroups)
            {
                _context.Add(memberInGroup);
            }
            setting.Groupsets.Add(groupSet);
            //newGroupSet.RandomizeGroupByNumber(relations, setting.Persons.ToArray(), input.GroupCount);
            await _context.SaveChangesAsync();
            //var setting = _context.Settings.SingleOrDefault(m => m.Id == p.SettingId);
            //setting.Persons.Add(p);
            //_context.SaveChanges();
            //return Json(new { Id = p.Id, Name = p.Name });

            ViewData["Setting"] = setting;
            ViewData["GroupSets"] = setting.Groupsets.ToList();
            var groups = new List<Group>();
            var membersInAllGroups = new List<MembersInGroups>();
            foreach (var groupset in setting.Groupsets) //get all groups in setting
            {
                groups.AddRange(groupSet.Groups);
                foreach (var group in groupset.Groups)
                {
                    foreach (var memInGr in _context.MembersInGroups.Where(m => m.Group == group))
                    //get all member connections to this group
                    {
                        membersInAllGroups.Add(memInGr);
                    }
                }
            }
            //ViewData["Groups"] = groups;
            ViewData["MembersInGroups"] = membersInAllGroups;
            //ViewData["Persons"] = activePeople;
            return PartialView("_GroupSetList");
            //return Json("");
        }
    }
}

GroupyWeb/GroupyWeb/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GroupyWeb.Data;
using GroupyWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace GroupyWeb.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly GroupyContext _context;
        private UserManager<GroupyUser> _userManager;

        public SettingsController(GroupyContext context, UserManager<GroupyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        //private Task<GroupyUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Settings
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(this.User);
            var settings = _context.Settings.Include(s => s.Persons)
                .Where( s => s.GroupyUser == user);
            return View(await settings.ToListAsync());
            //return View(await _context.Settings.ToListAsync());
        }

        // GET: Settings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var setting = await _context.Settings
                .SingleOrDefaultAsync(m => m.Id == id);
            if (setting == null)
            {
                return NotFound();
            }

            return View(setting);
        }

        // GET: Settings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Settings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id")] Setting setting)
        {
            if (ModelState.IsValid)
            {
                
                var user = this.User;
                var user2 = await _userManager.GetUserAsync(user);
                setting.GroupyUser = user2;
                _context.Add(setting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(setting);
        }

        // GET: Settings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var setting = await _context.Settings.SingleOrDefaultAsync(m => m.Id == id);
            if (setting == null)
            {
                return NotFound();
            }
            return View(setting);
        }

        // POST: Settings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id")] Setting setting)
        {
            if (id != setting.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(setting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SettingExists(setting.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(setting);
        }

        // GET: Settings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var setting = await _context.Settings
                .SingleOrDefaultAsync(m => m.Id == id);
            if (setting == null)
            {
                return NotFound();
            }

            return View(setting);
        }

        // POST: Settings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var setting = await _context.Settings.SingleOrDefaultAsync(m => m.Id == id);
            _context.Settings.Remove(setting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SettingExists(int id)
        {
            return _context.Settings.Any(e => e.Id == id);
        }
    }
}

GroupyWeb/GroupyWeb/Views/Settings/Create.cshtml
@model GroupyWeb.Models.Setting

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Setting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GroupyWeb/GroupyWeb/Views/Settings/Delete.cshtml
@model GroupyWeb.Models.Setting

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Setting</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GroupyWeb/GroupyWeb/Views/Settings/Details.cshtml
@model GroupyWeb.Models.Setting

@{
    ViewData["Title"] = "Setting details";
}

<h2>Details</h2>

<div>
    <h4>Setting</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GroupyWeb/GroupyWeb/Views/Settings/Edit.cshtml
@model GroupyWeb.Models.Setting

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Setting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GroupyWeb/GroupyWeb/Views/Settings/Index.cshtml
@model IEnumerable<GroupyWeb.Models.Setting>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                Number of @Html.DisplayNameFor(model => model.Persons)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-area="" asp-controller="GroupMaker" asp-route-id="@item.Id">
                    @Html.DisplayFor(modelItem => item.Id)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Persons.Count)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>